apiVersion: apps/v1
kind: Deployment
metadata:
  name: maisaeducacao
spec:
  selector:
    matchLabels:
      app: maisaeducacao
  replicas: 1
  template:
    metadata:
      labels:
        app: maisaeducacao
    spec:
      containers:
        - name: maisaeducacao
          image: despossivel/maisaeducacao:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred


 
