version: "2"
services:
  db:
    container_name: postgres
    image: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - maisaeducacao
networks:
  maisaeducacao:
    driver: bridge
